config/routes.rb
Rails.application.routes.draw do

resources :posts do
  resources :comments
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

before_action :find_post, :only=>[:update, :destroy, :create]

  def create
    @comment=Comment.new(comment_params)
    if @comment.save
      flash[:notice]="Create Succeeded"
      redirect_to post_path(@post)
    else
      @comments=Comment.all
      render :action=>:show
    end
  end

  def update
    if @comment.update(comment_params)
      flash[:notice]="Update Succeeded"
      redirect_to post_path(@post)
    else
      render :action=>:show
    end
  end

  def destroy
    @comment.destroy
    flash[:alert] = "Delete Succeeded"
    redirect_to post_path(@post)
  end


  protected

  def find_post
    @post=Post.find(params[:id])
  end

  def comment_params
      params.require(:comment).permit(:speech, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :find_post, :only=>[:destroy, :edit, :update, :show]

  def index
    @posts=Post.all
    @post=Post.new
  end

  def update
    if @post.update(post_params)
      flash[:notice]="Update Succeeded"
      redirect_to posts_path
    else
      render :action=>:edit
    end
  end

  def edit

  end

  def create
    @post=Post.new(post_params)
    if @post.save
      flash[:notice]="Create Succeeded"
      redirect_to posts_path
    else
      @posts=Post.all
      render :action=>:index
    end
  end

  def show
    @comments=@post.comments
    @comment=Comment.new
  end

  def destroy
    @post.destroy
    flash[:alert] = "Delete Succeeded"
    redirect_to posts_path
  end

  protected

  def find_post
    @post=Post.find(params[:id])
  end

  def post_params
      params.require(:post).permit(:topic, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crisis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h2>Editing Page</h2>

<%=form_for @post, :url=>post_path(@post), :method=>:patch, :class=>"form" do |f|%>
<%=f.label :topic, "Topic"%>
<%=f.text_field :topic, :class=>"form-control"%>
<%=f.label :content, "Content"%>
<%=f.text_area :content, :class=>"form-control"%>
<%=f.submit "Update"%>
<%end%>

app/views/posts/index.html.erb
<h1>Crisis Posts</h1>
<br>
<br>

<table class="table">

  <tr>
    <th>Topics</th>

    <th>Actions</th>
  </tr>
  <%@posts.each do |p|%>
  <tr>
    <td><%=p.topic%></td>
    <td>
      <%=link_to "Show", post_path(p), :class=>"btn btn-primary"%>
      <%=link_to "Destroy", post_path(p), :method=>:delete, :class=>"btn btn-primary"%>
    </td>
  </tr>
  <%end%>
</table>

<br>
<br>
<p>Create a New Post</p>
<br>
<%=form_for @post, :url=>posts_path(@post), :class=>"form" do |f|%>
<%=f.label :topic, "Topic"%>
<%=f.text_field :topic, :class=>"form-control"%>
<%=f.label :content, "Content"%>
<%=f.text_area :content, :class=>"form-control"%>
<%=f.submit "Create"%>
<%end%>

app/views/posts/show.html.erb
<h1>Crisis Details</h1>
<br>
<h3>Topic:</h3>
<br>
<%=@post.topic%>
<br>
<h3>Content</h3>
<br>
<%=@post.content%>
<br>
<br>
<%=link_to "Back to Main", posts_path, :class=>"btn btn-primary"%>
<%=link_to "Edit", edit_post_path(@post), :class=>"btn btn-primary"%>
<br>
<br>

<table class="table">
  <tr>
    <th>Comments</th>

    <th>Actions</th>
  </tr>
  <%@comments.each do |c|%>
  <tr>
    <td><%=c.speech%></td>
    <td>
      <%=link_to "Destroy", post_comment_path(c), :method=>:delete, :class=>"btn btn-primary"%>
    </td>
  </tr>
  <%end%>
</table>
<br>
<br>
<h3>Leave a Comment</h2>
  <%=form_for @comment, :url => post_comments_path(@post), :class=>"form" do |x|%>
  <%=x.text_area :speech, :class=>"form-control"%>
  <%=x.submit "Create"%>
  <%end%>